aliases:
    apply-ghanima: nix run --impure home-manager/master -- -b bak switch --flake .#bjk@ghanima
    fleeks: cd /var/home/bjk/projects/ublue/fleek/examples/high
bling: high
ejected: true
flakedir: projects/ublue/fleek/examples/high
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
name: Fleek Configuration
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: ghanima
      os: linux
      username: bjk
unfree: true
